### ISSUE TITLE
variables in attributes don't get replaced

### ISSUE THREAD

**Issue by alaricd** [gruntjs/grunt-contrib-pug#167] opened 2016-05-09 18:42 UTC
```
doctype html
html(lang='en')
    head
        meta(charset='UTF-8')
        title
            | Votron
        meta(name='viewport', content='width=device-width, initial-scale=1')
        meta(http-equiv='X-UA-Compatible', content='IE=edge')
        link(rel='stylesheet', href='css/app.css')
        //link(rel='stylesheet', href='#{appcss}')
        script(type='text/javascript', src='#{dest}')
        script(type='text/javascript', src="#{applibscript}")

    body(ng-app="app", ng-controller="PageController as pc", ng-class="pc.bodyClass"
         data-pug-environment="#{environment}" data-state-name="{{$state.current.name}}")

        .ui-view
        #{dest}
        #{applibscript}
        script(type='text/javascript', src='app/app.js')
        //script(type='text/javascript', src='#{appscript}')
```

Generates the following HTML
```

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Votron</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="css/app.css">
    <!--link(rel='stylesheet', href='#{appcss}')-->
    <script type="text/javascript" src="#{dest}"></script>
    <script type="text/javascript" src="#{applibscript}"></script>
  </head>
  <body ng-app="app" ng-controller="PageController as pc" ng-class="pc.bodyClass" data-pug-environment="#{environment}" data-state-name="{{$state.current.name}}">
    <div class="ui-view"></div>
    <fasdf></fasdf>
    <app/applib.js></app/applib.js>
    <script type="text/javascript" src="app/app.js"></script>
    <!--script(type='text/javascript', src='#{appscript}')-->
  </body>
</html>
```

As you can see, variables are working, but not withing the attributes.  This worked until we moved from grunt-contrib-jade to grunt-contrib-pug.

**Comment by shinnn** [comment] 2016-05-11 16:05
Duplicate of https://github.com/gruntjs/grunt-contrib-pug/issues/166.

**Closed by shinnn** 2016-05-11 16:05 UTC
